using System;
using System.Collections.Generic;
using Microsoft.Data.SqlClient;
using DevCoreHospital.Models;
using DevCoreHospital.Data;

namespace DevCoreHospital.Repositories
{
    public class HangoutRepository
    {
        private readonly ISqlConnectionFactory _connectionFactory;

        public HangoutRepository()
        {
            // Use your project's connection factory to get access to the actual DB
            _connectionFactory = new SqlConnectionFactory();
        }

        public void AddHangout(Hangout hangout)
        {
            using var conn = _connectionFactory.Create();
            conn.Open();

            using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
                INSERT INTO Hangouts (title, description, date_time, max_staff)
                OUTPUT INSERTED.hangout_id
                VALUES (@Title, @Description, @Date, @MaxStaff);
            ";

            cmd.Parameters.AddWithValue("@Title", hangout.title);
            cmd.Parameters.AddWithValue("@Description", string.IsNullOrEmpty(hangout.description) ? (object)DBNull.Value : hangout.description);
            cmd.Parameters.AddWithValue("@Date", hangout.date);
            cmd.Parameters.AddWithValue("@MaxStaff", hangout.maxParticipants);

            // ExecuteScalar returns the ID generated by IDENTITY(1,1)
            int newId = (int)cmd.ExecuteScalar();

            // Add any participants that were initialized with this hangout (like the creator)
            foreach (var p in hangout.participantList)
            {
                AddParticipant(newId, p.StaffID, conn);
            }
        }

        public void AddParticipant(int hangoutId, int staffId)
        {
            using var conn = _connectionFactory.Create();
            conn.Open();
            AddParticipant(hangoutId, staffId, conn);
        }

        // Helper method to keep inserts transactional/shared within the same connection scope
        private void AddParticipant(int hangoutId, int staffId, SqlConnection conn)
        {
            using var cmd = conn.CreateCommand();
            cmd.CommandText = "INSERT INTO Hangout_Participants (hangout_id, staff_id) VALUES (@HId, @SId)";
            cmd.Parameters.AddWithValue("@HId", hangoutId);
            cmd.Parameters.AddWithValue("@SId", staffId);
            cmd.ExecuteNonQuery();
        }

        public List<Hangout> GetAllHangouts()
        {
            var list = new List<Hangout>();
            using var conn = _connectionFactory.Create();
            conn.Open();

            using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT hangout_id, title, description, date_time, max_staff FROM Hangouts";

            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                int id = reader.GetInt32(0);
                string title = reader.GetString(1);
                string desc = reader.IsDBNull(2) ? "" : reader.GetString(2);
                DateTime date = reader.GetDateTime(3);
                int maxParticipants = reader.GetInt32(4);

                var h = new Hangout(id, title, desc, date, maxParticipants);
                list.Add(h);
            }
            reader.Close();

            // Populate the participant list for each hangout
            foreach (var h in list)
            {
                LoadParticipants(h, conn);
            }

            return list;
        }

        public Hangout? GetHangoutById(int id)
        {
            using var conn = _connectionFactory.Create();
            conn.Open();

            using var cmd = conn.CreateCommand();
            cmd.CommandText = "SELECT hangout_id, title, description, date_time, max_staff FROM Hangouts WHERE hangout_id = @Id";
            cmd.Parameters.AddWithValue("@Id", id);

            using var reader = cmd.ExecuteReader();
            if (reader.Read())
            {
                string title = reader.GetString(1);
                string desc = reader.IsDBNull(2) ? "" : reader.GetString(2);
                DateTime date = reader.GetDateTime(3);
                int maxParticipants = reader.GetInt32(4);

                var h = new Hangout(id, title, desc, date, maxParticipants);
                reader.Close();

                LoadParticipants(h, conn);
                return h;
            }
            return null;
        }

        private void LoadParticipants(Hangout h, SqlConnection conn)
        {
            using var cmd = conn.CreateCommand();
            cmd.CommandText = @"
                SELECT s.staff_id, s.first_name, s.last_name 
                FROM Hangout_Participants hp
                JOIN Staff s ON hp.staff_id = s.staff_id
                WHERE hp.hangout_id = @HId";
            cmd.Parameters.AddWithValue("@HId", h.hangoutID);

            using var reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                int sId = reader.GetInt32(0);
                string fName = reader.GetString(1);
                string lName = reader.GetString(2);

                // We use a general IStaff representation just to have the ID & names accessible. 
                h.participantList.Add(new Doctor { StaffID = sId, FirstName = fName, LastName = lName });
            }
        }
    }
}